on:
  pull_request:
  push:
    branches:
      - master
jobs:
  validate-jvm:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v3
    - uses: coursier/cache-action@v5
      with:
        extraKey: validate-jvm
    - run: ./scripts/validate-jvm.sh
  coverage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v3
    - uses: coursier/cache-action@v5
      with:
        extraKey: coverage
    - run: ./scripts/coverage.sh
  validate-js:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v3
    - uses: coursier/cache-action@v5
      with:
        extraKey: validate-js
    - run: ./scripts/validate-js.sh
