on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test-jvm:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v2
    - uses: coursier/cache-action@v4.1
    - run: |
        ./scripts/builds.sh lint
        ./scripts/builds.sh testJVM
        ./scripts/builds.sh docs
  coverage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v2
    - uses: coursier/cache-action@v4.1
    - run: ./scripts/builds.sh coverage
  test-js:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v2
    - uses: coursier/cache-action@v4.1
    - run: ./scripts/builds.sh testJS
