on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: nixbuild/nix-quick-install-action@v3
    - uses: coursier/cache-action@v5
      with:
        extraKey: release
    - run: ./scripts/release.sh
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
